create or replace PROCEDURE AddBookBasket
(BKISBNNO IN VARCHAR,BKID OUT INTEGER,BKNAME OUT VARCHAR,BKAUTHOR OUT VARCHAR,BKPUBLICATION OUT VARCHAR,BKGENRE OUT VARCHAR,
BKPRICE OUT NUMBER,BKLANG OUT VARCHAR,BKISBN OUT VARCHAR,ISINVENTORY OUT INTEGER)
IS
ISAVAILABLE INTEGER;
BEGIN
SELECT INVENTORY INTO ISAVAILABLE FROM TBOOK WHERE ISBN=BKISBNNO;
IF ISAVAILABLE>0 THEN 

SELECT A.BOOKID,A.BOOKNAME,A.AUTHOR,B.HOUSENAME,C.GENREDESC,A.PRICE,D.LANGNAME,A.ISBN,1
INTO BKID,BKNAME,BKAUTHOR,BKPUBLICATION,BKGENRE,BKPRICE,BKLANG,BKISBN,ISINVENTORY
FROM tBOOK A 
INNER JOIN MPUBLICATIONHOUSE B ON A.PUBLICATIONHOUSE=B.HOUSEID
INNER JOIN MGENRE C ON A.GENRE=C.GENREID
INNER JOIN MLANGUAGE D ON A.LANGUAGE=D.LANGID
WHERE A.ISBN=BKISBNNO;

ELSE

SELECT A.BOOKID,A.BOOKNAME,A.AUTHOR,B.HOUSENAME,C.GENREDESC,A.PRICE,D.LANGNAME,A.ISBN,0
INTO BKID,BKNAME,BKAUTHOR,BKPUBLICATION,BKGENRE,BKPRICE,BKLANG,BKISBN,ISINVENTORY
FROM tBOOK A 
INNER JOIN MPUBLICATIONHOUSE B ON A.PUBLICATIONHOUSE=B.HOUSEID
INNER JOIN MGENRE C ON A.GENRE=C.GENREID
INNER JOIN MLANGUAGE D ON A.LANGUAGE=D.LANGID
WHERE A.ISBN=BKISBNNO;
END IF;
END AddBookBasket;