ALTER TABLE MEMPLOYEE
ADD CONSTRAINT EMPUSERNAME_unique UNIQUE (USERNAME);

ALTER TABLE TCUSTOMER
ADD CONSTRAINT EMAILID_unique UNIQUE (EMAILID);

ALTER TABLE MPAYMENTMETHOD
ADD CONSTRAINT PMETHOD_unique UNIQUE (PAYMETHOD);

ALTER TABLE MGENRE
ADD CONSTRAINT GENRE_unique UNIQUE (GENREDESC);

ALTER TABLE MGENDER
ADD CONSTRAINT GENDER_unique UNIQUE (GENDER);

ALTER TABLE MLANGUAGE
ADD CONSTRAINT LANG_unique UNIQUE (LANGNAME);


