create or replace PROCEDURE INSERTTRANS(CUSTEMAIL IN VARCHAR,PAYMETHOD IN INTEGER,BKONEID IN INTEGER,BKONEQTY IN INTEGER,BKTWOID IN INTEGER,
BKTWOQTY IN INTEGER,BKTHREEID IN INTEGER,BKTHREEQTY IN INTEGER,TOTPRICE IN NUMBER,INVPROBLEM OUT INTEGER,ISINSERTCOMPL OUT INTEGER )
IS 
--DECLARE LOCAL VARIABLES
BKONEINV INTEGER;
BKTWOINV INTEGER;
BKTHREEINV INTEGER;
CUSTID INTEGER;
MAXTRANSID NUMBER;
DATE_today DATE;
TOTQUANTITY INTEGER;
ROWSINSERTED INTEGER;
BEGIN
SELECT  INVENTORY INTO  BKONEINV  FROM TBOOK WHERE BOOKID=BKONEID;
SELECT  INVENTORY INTO  BKTWOINV  FROM TBOOK WHERE BOOKID=BKTWOID;
SELECT  INVENTORY INTO  BKTHREEINV  FROM TBOOK WHERE BOOKID=BKTHREEID;
SELECT CUSTOMERID INTO CUSTID FROM TCUSTOMER WHERE EMAILID=CUSTEMAIL;
SELECT MAX(TRANSID) INTO MAXTRANSID FROM TCUSTOMERTRANSACTION;
SELECT SYSDATE INTO DATE_today FROM DUAL;
TOTQUANTITY:=BKONEQTY+BKTWOQTY+BKTHREEQTY;

IF BKONEQTY>BKONEINV THEN
  INVPROBLEM:=1;
ELSIF BKTWOQTY>BKTWOINV THEN
  INVPROBLEM:=2;
ELSIF BKTHREEQTY>BKTHREEINV THEN
  INVPROBLEM:=3;
ELSE
  INVPROBLEM:=0;
END IF;
  
IF   INVPROBLEM=0 THEN 
INSERT INTO TCUSTOMERTRANSACTION (TRANSID,TRANSDATE,TRANSAMOUNT,CUSTOMERID,PAYMENTMETHOD,QUANTITY)
VALUES (MAXTRANSID+1,DATE_today,TOTPRICE,CUSTID,PAYMETHOD,TOTQUANTITY);
ROWSINSERTED :=sql%rowcount;

IF BKONEID<>0 AND ROWSINSERTED=1 THEN
ISINSERTCOMPL:=SINGLEBOOKTRANS(MAXTRANSID+1,BKONEID,BKONEQTY);
END IF;

IF BKTWOID<>0 AND ROWSINSERTED=1 THEN
ISINSERTCOMPL:=SINGLEBOOKTRANS(MAXTRANSID+1,BKTWOID,BKTWOQTY);
END IF;


IF BKTHREEID<>0 AND ROWSINSERTED=1 THEN
ISINSERTCOMPL:=SINGLEBOOKTRANS(MAXTRANSID+1,BKTHREEID,BKTHREEQTY);
END IF;
ELSE
ISINSERTCOMPL:=2;
END IF;
END INSERTTRANS;