create or replace FUNCTION SINGLEBOOKTRANS (BKTRANSACTIONID IN NUMBER, BKID IN NUMBER, BKQUANTITY IN NUMBER)
RETURN INTEGER
IS ISINSERTED INTEGER;
MAXDETAILID INTEGER;
BKUNITPRICE NUMBER;
BKTOTALPRICE NUMBER;
v_today DATE;
ROWSINSERTED number;
BEGIN
SELECT SYSDATE INTO v_today FROM DUAL;
SELECT PRICE INTO BKUNITPRICE FROM TBOOK WHERE BOOKID=BKID;
BKTOTALPRICE:=BKUNITPRICE*BKQUANTITY;
SELECT MAX(DETAILID)INTO MAXDETAILID FROM TTRANSACTIONDETAILS;
UPDATE TBOOK SET INVENTORY =INVENTORY-BKQUANTITY WHERE BOOKID=BKID;
INSERT INTO TTRANSACTIONDETAILS (DETAILID,TRANSID,BOOKID,BOOKUNITPRICE,QUANTITY,TOTALPRICE,TRANSDATE)
VALUES (MAXDETAILID+1,BKTRANSACTIONID,BKID,BKUNITPRICE,BKQUANTITY,BKTOTALPRICE,v_today);
ROWSINSERTED :=sql%rowcount;
IF ROWSINSERTED=1 THEN
ISINSERTED:=1;
ELSE
ISINSERTED:=0;
END IF;
RETURN ISINSERTED;
END SINGLEBOOKTRANS;