create or replace PROCEDURE validateEmployee 
(EUsername IN VARCHAR, EPassword IN VARCHAR, Role OUT INTEGER)
IS
BEGIN
SELECT ROLEID into Role FROM MEMPLOYEE WHERE USERNAME=EUSERNAME AND PASSWORD=EPASSWORD AND ISACTIVE=1;
END validateEmployee;